### ISSUE TITLE
Skript zum trennen in Trainings- und Testdatensätze von gelabelten Quellbildern

### ISSUE THREAD

**Issue by B1tstorm** [B1tstorm/ki-anwendung_object-detection#4]
Die Bilder, welche von der KI vorsortiert wurden, müssen nun in Trainingsdaten und Testdaten getrennt werden.

**Comment by B1tstorm** [comment]
Die durch labelstudio exportierten Datensätze im pascal Format, sollen nun zu 90% zum trainieren und zu 10% zum testen getrennt werden. Damit lassen sich die Modelle später vergleichen, mit den selben Trainings- und Testdaten.

**Comment by AnasAr96** [comment]
gelöst in Datei "Scripts/split_datasets_in_test_and_train.ipynb"
